Repository AY2122S1-CS2113T-T12-1/tp, pull requests merged in 2021-10, with the labels that each got.

#30 Added greeting
  src/main/java/seedu/mtracker/MTracker.java
  src/main/java/seedu/mtracker/ui/TextUi.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Task, priority.High

#32 Added add Forex feature
  src/main/java/seedu/mtracker/commands/AddForexCommand.java
  src/main/java/seedu/mtracker/console/AddForexParser.java
  src/main/java/seedu/mtracker/console/AddInstrumentParser.java
  src/main/java/seedu/mtracker/instrument/subinstrument/Forex.java
  src/main/java/seedu/mtracker/ui/TextUi.java
Labels: type.Story, priority.High

#35 Main program logic
  src/main/java/seedu/mtracker/MTracker.java
  src/main/java/seedu/mtracker/commands/InvalidCommand.java
  src/main/java/seedu/mtracker/console/InputParser.java
  src/main/java/seedu/mtracker/ui/TextUi.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Task, priority.High

#38 Added AddCryptoParser Junit test
  src/main/java/seedu/mtracker/error/ErrorMessage.java
  src/test/java/seedu/mtracker/console/AddCryptoParserTest.java
  src/test/java/seedu/mtracker/console/AddStockParserTest.java
Labels: type.Task, priority.High

#41 Added Junit tests for AddForexParser and updated error message for invalid fx name
  src/main/java/seedu/mtracker/console/AddInstrumentParser.java
  src/main/java/seedu/mtracker/error/ErrorMessage.java
  src/test/java/seedu/mtracker/console/AddForexParserTest.java
Labels: type.Task, priority.High

#49 Assertions added for AddForexParser
  src/main/java/seedu/mtracker/asserthelpers/AssertParserHelper.java
  src/main/java/seedu/mtracker/console/AddForexParser.java
Labels: type.Task, priority.High

#55 Add Assertion for Etf Parser
  src/main/java/seedu/mtracker/asserthelpers/AssertParserHelper.java
  src/main/java/seedu/mtracker/console/AddEtfParser.java
Labels: type.Task, priority.Low

#81 Enable assertions in build.gradle file
  build.gradle
  logger.log.lck
Labels: type.Task, priority.High

#89 Update architecture section in DG
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#93 Update UI component section in DG design
  docs/DeveloperGuide.md
Labels: type.Task, priority.Medium

#159 Remove unnecessary getters
  src/main/java/seedu/mtracker/model/Instrument.java
  src/main/java/seedu/mtracker/model/subinstrument/Crypto.java
  src/main/java/seedu/mtracker/model/subinstrument/Etf.java
  src/main/java/seedu/mtracker/model/subinstrument/Forex.java
Labels: type.Task, priority.Medium

#158 Abstract out indexed commands
  src/main/java/seedu/mtracker/commands/DeleteCommand.java
  src/main/java/seedu/mtracker/commands/DoneCommand.java
  src/main/java/seedu/mtracker/commands/EditInstrumentCommand.java
  src/main/java/seedu/mtracker/commands/IndexedCommand.java
  src/main/java/seedu/mtracker/commands/ViewCommand.java
  src/main/java/seedu/mtracker/commons/Validate.java
  src/main/java/seedu/mtracker/console/InputParser.java
  src/main/java/seedu/mtracker/error/AlreadyDoneError.java
  src/main/java/seedu/mtracker/error/ErrorMessage.java
  src/main/java/seedu/mtracker/model/Instrument.java
  src/main/java/seedu/mtracker/model/InstrumentManager.java
  src/test/java/seedu/mtracker/console/InputParserTest.java
Labels: type.Task, priority.High
