Repository AY2122S1-CS2113T-T12-1/tp, pull requests merged in 2021-11, with the labels that each got.

#202 Add current workspace to prompter
  src/main/java/seedu/mtracker/MTracker.java
  src/main/java/seedu/mtracker/console/AddCryptoParser.java
  src/main/java/seedu/mtracker/console/AddEtfParser.java
  src/main/java/seedu/mtracker/console/AddForexParser.java
  src/main/java/seedu/mtracker/console/AddInstrumentParser.java
  src/main/java/seedu/mtracker/console/AddStockParser.java
  src/main/java/seedu/mtracker/console/EditInstrumentParser.java
  src/main/java/seedu/mtracker/console/InputParser.java
  src/main/java/seedu/mtracker/ui/TextUi.java
  text-ui-test/EXPECTED.TXT
Labels: type.Enhancement, type.Task, priority.Medium

#198 added exception to handle negative or 0 current price. Added ability to run multiple invalid inputs into instrument type
  src/main/java/seedu/mtracker/commons/Validate.java
  src/main/java/seedu/mtracker/console/InputParser.java
  src/main/java/seedu/mtracker/error/ErrorMessage.java
  src/main/java/seedu/mtracker/error/InvalidNegativePriceError.java
  src/main/java/seedu/mtracker/error/InvalidPriceError.java
Labels: type.Bug, priority.Low

#199 changed file separator
  src/main/java/seedu/mtracker/filemanager/InstrumentDecoder.java
  src/main/java/seedu/mtracker/model/Instrument.java
Labels: type.Bug, priority.High, severity.High

#203 Abstract out AddInstrumentParserTest
  src/test/java/seedu/mtracker/console/AddCryptoParserTest.java
  src/test/java/seedu/mtracker/console/AddEtfParserTest.java
  src/test/java/seedu/mtracker/console/AddForexParserTest.java
  src/test/java/seedu/mtracker/console/AddInstrumentParserTest.java
  src/test/java/seedu/mtracker/console/AddStockParserTest.java
  src/test/java/seedu/mtracker/console/InputParserTest.java
Labels: type.Task, priority.High

#204 added lowercase functionality for all commands and fixed params
  src/main/java/seedu/mtracker/console/AddInstrumentParser.java
  src/main/java/seedu/mtracker/console/InputParser.java
Labels: type.Enhancement, priority.Low

#205 Enable find with more than one search word
  src/main/java/seedu/mtracker/commands/FindCommand.java
  src/main/java/seedu/mtracker/console/InputParser.java
  src/main/java/seedu/mtracker/error/InvalidEmptySearchStringError.java
  src/main/java/seedu/mtracker/ui/TextUi.java
Labels: type.Task, type.Bug, priority.Medium, severity.High

#206 Specific error messages
  src/main/java/seedu/mtracker/commons/Validate.java
  src/main/java/seedu/mtracker/error/ErrorMessage.java
Labels: type.Task, type.Bug, priority.Medium, severity.Medium

#213 Add abort and its testing
  src/main/java/seedu/mtracker/MTracker.java
  src/main/java/seedu/mtracker/asserthelpers/AssertOperationHelper.java
  src/main/java/seedu/mtracker/commons/Validate.java
  src/main/java/seedu/mtracker/console/AddCryptoParser.java
  src/main/java/seedu/mtracker/console/AddEtfParser.java
  src/main/java/seedu/mtracker/console/AddForexParser.java
  src/main/java/seedu/mtracker/console/AddInstrumentParser.java
  src/main/java/seedu/mtracker/console/AddStockParser.java
  src/main/java/seedu/mtracker/console/EditInstrumentParser.java
  src/main/java/seedu/mtracker/console/InputParser.java
  src/main/java/seedu/mtracker/error/ErrorMessage.java
  src/main/java/seedu/mtracker/error/OperationAbortedError.java
  src/test/java/seedu/mtracker/commons/ValidateTest.java
  src/test/java/seedu/mtracker/console/AddCryptoParserTest.java
  src/test/java/seedu/mtracker/console/AddEtfParserTest.java
  src/test/java/seedu/mtracker/console/AddForexParserTest.java
  src/test/java/seedu/mtracker/console/AddInstrumentParserTest.java
  src/test/java/seedu/mtracker/console/AddStockParserTest.java
  src/test/java/seedu/mtracker/console/InputParserTest.java
Labels: type.Enhancement, type.Task, priority.High

#207 Add tests for expiry
  src/test/java/seedu/mtracker/console/AddCryptoParserTest.java
  src/test/java/seedu/mtracker/console/AddForexParserTest.java
  src/test/java/seedu/mtracker/console/AddInstrumentParserTest.java
  src/test/java/seedu/mtracker/console/AddStockParserTest.java
Labels: type.Task, priority.Medium

#138 Junit For Edit parser and Some Bug Fixing Of Edit
  src/main/java/seedu/mtracker/commons/Validate.java
  src/main/java/seedu/mtracker/console/EditInstrumentParser.java
  src/main/java/seedu/mtracker/console/InputParser.java
  src/main/java/seedu/mtracker/error/EditEmptyParameterError.java
  src/main/java/seedu/mtracker/error/ErrorMessage.java
  src/main/java/seedu/mtracker/error/InvalidStatusError.java
  src/main/java/seedu/mtracker/model/Instrument.java
  src/main/java/seedu/mtracker/model/subinstrument/Etf.java
  src/main/java/seedu/mtracker/ui/TextUi.java
  src/test/java/seedu/mtracker/console/AddCryptoParserTest.java
  src/test/java/seedu/mtracker/console/AddEtfParserTest.java
  src/test/java/seedu/mtracker/console/AddForexParserTest.java
  src/test/java/seedu/mtracker/console/AddStockParserTest.java
  src/test/java/seedu/mtracker/console/EditInstrumentParserTest.java
  src/test/java/seedu/mtracker/console/GeneralInstrumentParserTest.java
Labels: priority.Medium

#153 Added implementation for filemanager
  docs/DeveloperGuide.md
  docs/diagrams/Colors.puml
  docs/diagrams/DoneCryptoExecuteDiagram.puml
  docs/diagrams/DoneCryptoSequenceDiagram.puml
  docs/diagrams/FileManagerDiagram.puml
  docs/diagrams/FileManagerEncodingSequenceDiag.puml
  docs/diagrams/FileManagerRefDiagCryptoDecoder.puml
  docs/diagrams/FileManagerSeqBetweenStorageAndDecoder.puml
  docs/diagrams/FileManagerSequenceDiagram.puml
  docs/images/DoneCryptoExecuteDiagram.png
  docs/images/DoneCryptoSequenceDiagram.png
  docs/images/FileManagerDiagram.png
  docs/images/FileManagerEncodingSequenceDiag.png
  docs/images/FileManagerRefDiagCryptoDecoder.png
  docs/images/FileManagerSeqBetweenStorageAndDecoder.png
  docs/images/FileManagerSequenceDiagram.png
Labels: type.Task, priority.High

#221 Added ppp
  docs/team/williamlamjy.md
Labels: type.Task, priority.High

#233 added java docs for filemanager
  src/main/java/seedu/mtracker/filemanager/CryptoDecoder.java
  src/main/java/seedu/mtracker/filemanager/EtfDecoder.java
  src/main/java/seedu/mtracker/filemanager/ForexDecoder.java
  src/main/java/seedu/mtracker/filemanager/InstrumentDecoder.java
  src/main/java/seedu/mtracker/filemanager/InstrumentEncoder.java
  src/main/java/seedu/mtracker/filemanager/StockDecoder.java
  src/main/java/seedu/mtracker/filemanager/Storage.java
Labels: type.Task, priority.High

#222 JavaDoc for edited class
  src/main/java/seedu/mtracker/commands/EditInstrumentCommand.java
  src/main/java/seedu/mtracker/console/EditInstrumentParser.java
Labels: priority.Medium

#229 Add javadocs for console
  src/main/java/seedu/mtracker/console/AddCryptoParser.java
  src/main/java/seedu/mtracker/console/AddEtfParser.java
  src/main/java/seedu/mtracker/console/AddForexParser.java
  src/main/java/seedu/mtracker/console/AddInstrumentParser.java
  src/main/java/seedu/mtracker/console/AddStockParser.java
  src/main/java/seedu/mtracker/console/EditInstrumentParser.java
  src/main/java/seedu/mtracker/console/InputParser.java
Labels: priority.High

#152 added userstories to dg
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#237 Added java docs for validate
  src/main/java/seedu/mtracker/commons/Validate.java
  src/main/java/seedu/mtracker/commons/error/InvalidPastReturnsError.java
  src/main/java/seedu/mtracker/commons/error/InvalidPastReturnsTypeError.java
Labels: priority.High

#231 Add TextUi seq diagrams and explanation
  docs/DeveloperGuide.md
  docs/diagrams/TextUiDisplayInstrumentAllParams.puml
  docs/diagrams/TextUiDisplayInstrumentGeneralParams.puml
  docs/images/TextUiDisplayInstrumentAllParams.png
  docs/images/TextUiDisplayInstrumentGeneralParams.png
Labels: type.Task, priority.High

#214 Add Vignesh PPP
  docs/team/kvignesh122.md
Labels: type.Task, priority.High

#238 Add command class diagram
  docs/DeveloperGuide.md
  docs/diagrams/CommandsDiagram.puml
  docs/diagrams/Styles.puml
  docs/images/CommandsDiagram.png
Labels: type.Task, priority.High

#242 Update AboutUs
  docs/AboutUs.md
  docs/README.md
  docs/images/Theodore.png
  docs/images/Vignesh.jpeg
  docs/images/William.png
  docs/images/WingHo.png
Labels: type.Task, priority.Medium

#220 Add my author tags
  src/main/java/seedu/mtracker/asserthelpers/AssertOperationHelper.java
  src/main/java/seedu/mtracker/commands/AddForexCommand.java
  src/main/java/seedu/mtracker/commands/ExitCommand.java
  src/main/java/seedu/mtracker/commands/FindCommand.java
  src/main/java/seedu/mtracker/commands/IndexedCommand.java
  src/main/java/seedu/mtracker/commands/InvalidCommand.java
  src/main/java/seedu/mtracker/commands/ViewCommand.java
  src/main/java/seedu/mtracker/commons/Validate.java
  src/main/java/seedu/mtracker/commons/error/AlreadyDoneError.java
  src/main/java/seedu/mtracker/commons/error/InvalidEmptyExpiryDateError.java
  src/main/java/seedu/mtracker/commons/error/InvalidEmptySearchStringError.java
  src/main/java/seedu/mtracker/commons/error/InvalidNameError.java
  src/main/java/seedu/mtracker/commons/error/OperationAbortedError.java
  src/main/java/seedu/mtracker/console/AddForexParser.java
  src/main/java/seedu/mtracker/console/InputParser.java
  src/main/java/seedu/mtracker/model/Instrument.java
  src/main/java/seedu/mtracker/model/subinstrument/Forex.java
  src/main/java/seedu/mtracker/ui/TextUi.java
  src/test/java/seedu/mtracker/console/AddCryptoParserTest.java
  src/test/java/seedu/mtracker/console/AddEtfParserTest.java
  src/test/java/seedu/mtracker/console/AddForexParserTest.java
  src/test/java/seedu/mtracker/console/AddStockParserTest.java
  src/test/java/seedu/mtracker/console/GeneralInstrumentParserTest.java
  src/test/java/seedu/mtracker/console/InputParserTest.java
Labels: type.Task, priority.Medium

#224 Fix and update ug
  docs/UserGuide.md
Labels: priority.High

#245 add author tags
  src/main/java/seedu/mtracker/commands/AddCryptoCommand.java
  src/main/java/seedu/mtracker/commands/Command.java
  src/main/java/seedu/mtracker/commands/DoneCommand.java
  src/main/java/seedu/mtracker/commons/Validate.java
  src/main/java/seedu/mtracker/commons/error/ErrorMessage.java
  src/main/java/seedu/mtracker/commons/error/InvalidEmptyPriceError.java
  src/main/java/seedu/mtracker/commons/error/InvalidInstrumentError.java
  src/main/java/seedu/mtracker/commons/error/InvalidNegativePriceError.java
  src/main/java/seedu/mtracker/commons/error/fileerror/FileWriteError.java
  src/main/java/seedu/mtracker/commons/error/fileerror/InvalidCurrPriceSavedInFileError.java
  src/main/java/seedu/mtracker/commons/error/fileerror/InvalidEmptyCurrPriceInFileError.java
  src/main/java/seedu/mtracker/commons/error/fileerror/InvalidEmptyEntryPriceInFileError.java
  src/main/java/seedu/mtracker/commons/error/fileerror/InvalidEmptyExitPriceInFileError.java
  src/main/java/seedu/mtracker/commons/error/fileerror/InvalidEmptyExpiryInFileError.java
  src/main/java/seedu/mtracker/commons/error/fileerror/InvalidEmptyNameInFileError.java
  src/main/java/seedu/mtracker/commons/error/fileerror/InvalidEmptySentimentInFileError.java
  src/main/java/seedu/mtracker/commons/error/fileerror/InvalidEmptyStatusInFileError.java
  src/main/java/seedu/mtracker/commons/error/fileerror/InvalidEntryPriceSavedInFileError.java
  src/main/java/seedu/mtracker/commons/error/fileerror/InvalidExitPriceSavedInFileError.java
  src/main/java/seedu/mtracker/commons/error/fileerror/InvalidExpirySavedInFileError.java
  src/main/java/seedu/mtracker/commons/error/fileerror/InvalidInstrumentInFileError.java
  src/main/java/seedu/mtracker/commons/error/fileerror/InvalidNameSavedInFileError.java
  src/main/java/seedu/mtracker/commons/error/fileerror/InvalidPastReturnsSavedInFileError.java
  src/main/java/seedu/mtracker/commons/error/fileerror/InvalidRemarksInFileError.java
  src/main/java/seedu/mtracker/commons/error/fileerror/InvalidSentimentSavedInFileError.java
  src/main/java/seedu/mtracker/commons/error/fileerror/InvalidStatusSavedInFileError.java
  src/main/java/seedu/mtracker/console/AddCryptoParser.java
  src/main/java/seedu/mtracker/console/InputParser.java
  src/main/java/seedu/mtracker/filemanager/CryptoDecoder.java
  src/main/java/seedu/mtracker/filemanager/EtfDecoder.java
  src/main/java/seedu/mtracker/filemanager/ForexDecoder.java
  src/main/java/seedu/mtracker/filemanager/InstrumentDecoder.java
  src/main/java/seedu/mtracker/filemanager/InstrumentEncoder.java
  src/main/java/seedu/mtracker/filemanager/StockDecoder.java
  src/main/java/seedu/mtracker/filemanager/Storage.java
  src/main/java/seedu/mtracker/model/Instrument.java
  src/main/java/seedu/mtracker/model/InstrumentManager.java
  src/main/java/seedu/mtracker/model/subinstrument/Crypto.java
  src/main/java/seedu/mtracker/model/subinstrument/Etf.java
  src/main/java/seedu/mtracker/model/subinstrument/Forex.java
  src/main/java/seedu/mtracker/model/subinstrument/Stock.java
  src/main/java/seedu/mtracker/ui/TextUi.java
  src/test/java/seedu/mtracker/commons/ValidateTest.java
  src/test/java/seedu/mtracker/console/AddCryptoParserTest.java
  src/test/java/seedu/mtracker/console/InputParserTest.java
  src/test/java/seedu/mtracker/filemanager/ForexDecoderTest.java
  src/test/java/seedu/mtracker/filemanager/InstrumentDecoderTest.java
Labels: priority.Medium

#248 final edits to ug
  docs/UserGuide.md
Labels: priority.High

#249 Add javadoc to MTracker.java
  src/main/java/seedu/mtracker/MTracker.java
Labels: type.Task, priority.Medium
